# Generated by Django 2.2.4 on 2019-08-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190819_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='node_id',
        ),
    ]
